name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  applicationfolder: spring-boot-hello-world-example
  AWS_REGION: us-east-1
  S3BUCKET: codedeploystack-webappdeploymentbucket-gbgbspwbuw25


jobs:
  build:
    name: knocking out of gear
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: heating engine
        uses: actions/setup-java@v2
        with:
          java-version: 21.0.1
          distribution: 'zulu'

      - name: turnning the key
        run: chmod -R +x ./.github
